
/**
 * Defines the allowed roles for agents within the system.
 */
export type AgentRole = 'Planner' | 'Security' | 'Performance' | 'Style' | 'Sovereign' | 'Cartographer';

/**
 * Represents a specific persona profile an agent can adopt.
 * @property {string} id - Unique identifier for the persona.
 * @property {string} name - Display name of the persona.
 * @property {string} description - Brief description of the persona's focus or behavior.
 * @property {string} systemPrompt - The system prompt defining the persona's behavior for the LLM.
 */
export interface Persona {
  id: string;
  name: string;
  description: string;
  systemPrompt: string;
}

/**
 * Configuration mapping an agent role to a specific persona.
 * @property {AgentRole} role - The role assigned to the agent.
 * @property {string} personaId - The unique identifier of the selected persona for this role.
 */
export interface AgentConfig {
  role: AgentRole;
  personaId: string;
}

/**
 * Represents a message generated by an agent or the system within the workflow.
 * @property {string} id - Unique identifier for the message.
 * @property {AgentRole} role - The role of the agent that generated the message.
 * @property {string} personaName - The name of the persona that generated the message.
 * @property {string} content - The text content of the message.
 * @property {number} timestamp - Timestamp of when the message was generated.
 * @property {boolean} [isThinking] - Indicates if the agent is currently generating this message (optional).
 */
export interface AgentMessage {
  id: string;
  role: AgentRole;
  personaName: string;
  content: string;
  timestamp: number;
  isThinking?: boolean;
}

/**
 * Represents an entry in the architectural drift timeline.
 * @property {string} id - Unique identifier for the drift entry.
 * @property {string} timestamp - Timestamp of the drift event.
 * @property {string} summary - Brief summary of the drift or change.
 * @property {number} impactScore - An estimated impact score of the drift (0-100).
 * @property {string[]} affectedModules - List of system modules affected by this drift.
 */
export interface DriftEntry {
  id: string;
  timestamp: string;
  summary: string;
  impactScore: number; // 0-100
  affectedModules: string[];
}


/**
 * Represents a quarantined message due to high cognitive divergence (CFDI).
 * @property {string} id - Unique identifier for the escrow entry.
 * @property {string} timestamp - Timestamp when the entry was quarantined.
 * @property {AgentRole} role - The role of the agent that generated the quarantined message.
 * @property {string} personaName - The persona name of the agent.
 * @property {string} content - The content of the quarantined message.
 * @property {number} cfdiScore - The calculated Confidence-Fidelity Divergence Index score.
 * @property {'Quarantined'} status - The current status of the entry in escrow.
 */
export interface EscrowEntry {
  id: string;
  timestamp: string;
  role: AgentRole;
  personaName: string;
  content: string;
  cfdiScore: number;
  status: 'Quarantined';
}

/**
 * Represents a metric comparing the current state to a proposed target state.
 * @property {string} name - The name of the metric (e.g., 'Complexity', 'Coupling').
 * @property {number} before - The metric value before the proposed change.
 * @property {number} after - The predicted metric value after the proposed change.
 */
export interface DiffMetric {
  name: string;
  before: number;
  after: number;
}


/**
 * Represents a constraint generated from resolved conflicts to prevent future regressions.
 * In the context of VANCE, this also functions as the Nitinol Failure Ledger (NFL),
 * encoding past JSON-RPC malformation events as hard negative constraints.
 * @property {string} id - Unique identifier for the scar ratchet.
 * @property {string} sourceEscrowId - The ID of the escrow entry that precipitated this constraint.
 * @property {string} timestamp - Timestamp when the ratchet was created.
 * @property {string} constraint - The concise rule or constraint enforced by this ratchet.
 * @property {string} description - A detailed description of the rationale behind the constraint.
 */
export interface ScarRatchet {
  id: string;
  sourceEscrowId: string;
  timestamp: string;
  constraint: string;
  description: string;
}

/**
 * Represents a recorded architectural decision (ADR) in the decision log.
 * @property {string} id - Unique identifier for the decision record.
 * @property {string} timestamp - Timestamp of when the decision was made.
 * @property {string} title - The title or brief summary of the decision.
 * @property {'Active' | 'Superseded'} status - The current status of the decision.
 * @property {string[]} tags - Tags associated with the decision for categorization.
 */
export interface DecisionRecord {
  id: string;
  timestamp: string;
  title: string;
  status: 'Active' | 'Superseded';
  tags: string[];
}

/**
 * Represents the complete state of the architectural workflow application.
 * @property {'config' | 'orchestration' | 'consensus' | 'audit' | 'escrow'} step - The current active step in the UI workflow.
 * @property {string} goal - The primary architectural goal being evaluated.
 * @property {Record<AgentRole, string>} agentConfigs - Configuration mapping each agent role to its selected persona ID.
 * @property {boolean} deepThinkingEnabled - Indicates if deep reasoning (e.g., larger models/budgets) is enabled.
 * @property {boolean} webSearchEnabled - Indicates if web search capabilities are enabled for the agents.
 * @property {boolean} ddxEnabled - Controls whether the DDx Protocol (Exclusion Engine) is active.
 * @property {boolean} escrowEnabled - Indicates if the Epistemic Escrow system is active.
 * @property {EscrowEntry[]} escrowStore - The collection of quarantined messages.
 * @property {ScarRatchet[]} scarRegistry - The registry of active scar ratchets.
 * @property {AgentMessage[]} messages - The history of messages in the current workflow session.
 * @property {string | null} finalPlan - The final synthesized architectural plan, or null if not yet generated.
 * @property {DiffMetric[]} diffMetrics - The parsed metrics from the final consensus plan.
 * @property {boolean} isProcessing - Indicates if the system is currently processing an action.
 * @property {DriftEntry[]} driftTimeline - The history of architectural drift events.
 * @property {DecisionRecord[]} decisionLog - The log of recorded architectural decisions.
 */
export interface WorkflowState {
  step: 'config' | 'orchestration' | 'consensus' | 'audit' | 'escrow';
  goal: string;
  agentConfigs: Record<AgentRole, string>; // Role -> PersonaID
  deepThinkingEnabled: boolean;
  webSearchEnabled: boolean;
  ddxEnabled: boolean; // Controls DDx Protocol
  escrowEnabled: boolean;
  escrowStore: EscrowEntry[];
  scarRegistry: ScarRatchet[];
  messages: AgentMessage[];
  finalPlan: string | null;
  diffMetrics: DiffMetric[]; 
  isProcessing: boolean;
  driftTimeline: DriftEntry[];
  decisionLog: DecisionRecord[]; // For Stare Decisis
}

/**
 * Represents an event recorded in the system's audit log.
 * @property {string} id - Unique identifier for the audit event.
 * @property {string} timestamp - Timestamp of the event.
 * @property {string} action - The type of action that occurred.
 * @property {string} details - Detailed information about the event.
 * @property {'User' | 'System' | AgentRole} actor - The entity that triggered the event (User, System, or a specific AgentRole).
 */
export interface AuditEvent {
  id: string;
  timestamp: string;
  action: string;
  details: string;
  actor: 'User' | 'System' | AgentRole;
}